---
version: "2.0"
services:
  galaksio-quote:
    image: brandynham/galaksio-quote:latest
    expose:
      - port: 8081
        as: 80
        to:
          - global: true
profiles:
  compute:
    galaksio-quote:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 512Mi
        storage:
          - size: 1Gi
  placement:
    dcloud:
      pricing:
        galaksio-quote:
          denom: ibc/170C677610AC31DF0904FFE09CD3B5C657492170E7E52372E48756B71E56F2F1
          amount: 100000
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
        allOf: []
deployment:
  galaksio-quote:
    dcloud:
      profile: galaksio-quote
      count: 1
